---
services:
  db_micr:
    container_name: db_micr
    image: postgres:12
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # volumes:
    #   - ./var/pgdata:/var/lib/postgresql/data
    expose:
      - 5432

  api_micr:
    container_name: api_micr
    build:
      context: ../api
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db_micr
      - auth_micr
      - rmq_micr
    ports:
      - ${API_SEVICE_PORT}:${API_SEVICE_PORT}

  auth_micr:
    container_name: auth_micr
    build:
      context: ../auth
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db_micr:5432/${POSTGRES_DB}?schema=public
    restart: unless-stopped
    depends_on:
      - db_micr
      - rmq_micr

  rmq_micr:
    container_name: rmq_micr
    image: rabbitmq:3-management
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RMQ_PASSWORD}
    expose:
      - 5672
      - 15672
